version: '3.9'

volumes:
  mongo_data:

services:
  node:
    container_name: node_app
    image: node:18-alpine
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - ${SERVER_PORT}:3000
    command: npm run dev

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mongo_data:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
